### ISSUE TITLE
Problems for testing 

### ISSUE THREAD

**Issue by pp00704831** [huicongzhang/STDAN#1]
Hello, 

I test your model on the GoPro test set. However, there are some variables not defined in 'STDAN_Stack.py'. For example, the 'flow_forward_out' in line 57, 'flow_backward_out' in line 58, and the 'out' in line 59. Besides, a variable 'concated' in line 55 is not used in the model.
I can not test the code successfully, could you help me with what should I do for testing it successfully?

Looking forward to your reply! Thank you!

**Comment by huicongzhang** [comment]
Hello, 
This is a mistake in my release version. I've fixed the bug, please try again😊
