### ISSUE TITLE
The problem of build pytorch extension.

### ISSUE THREAD

**Issue by wgp666** [huicongzhang/STDAN#3]
The following error occurs when I build pytorch extension.

Traceback (most recent call last):
  File "setup.py", line 69, in <module>
    ext_modules=get_extensions(),
  File "setup.py", line 47, in get_extensions
    raise NotImplementedError('Cuda is not availabel')
NotImplementedError: Cuda is not availabel

**Comment by huicongzhang** [comment]
Do you have cudatoolkit installed?You can determine if cuda is installed by entering the following command "nvcc -V“
