### ISSUE TITLE
MultiScaleDeformableAttention is not found

### ISSUE THREAD

**Issue by Shan-Mu** [huicongzhang/STDAN#4]
MultiScaleDeformableAttention is not found.
這是不是你們不同於論文的改進，是否有匹配論文的原始版本的代碼？

**Comment by huicongzhang** [comment]
You can use the script to build PyTorch extensions [install.sh](https://github.com/huicongzhang/STDAN/blob/f826116b437380e5fca97d6a08b03f1e2ca6d0bf/install.sh)
